In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np

In [2]:
dataset1 = pd.read_csv('data.tsv', delimiter='\t', encoding='utf-8')
dataset2 = pd.read_csv('data-2.tsv', delimiter='\t', encoding='utf-8')
dataset3 = pd.read_csv('data-3.tsv', delimiter='\t', encoding='utf-8')
dataset4 = pd.read_csv('data-4.tsv', delimiter='\t', encoding='utf-8')
dataset5 = pd.read_csv('data-5.tsv', delimiter='\t', encoding='utf-8')
dataset6 = dataset5[(dataset5["category"] == "actor") | (dataset5["category"] == "actress") | (dataset5["category"] == "director")]
netflix = pd.read_csv('netflix_titles.csv')

/var/folders/fz/m2zqjdj93nlgb71yg16vfjwh0000gn/T/ipykernel_3072/173067345.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset2 = pd.read_csv('data-2.tsv', delimiter='\t', encoding='utf-8')

ParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 23

In [ ]:
# First, merge dataset1 and dataset2
merged_1_2 = pd.merge(dataset1, dataset2, on='tconst', how='inner')

# Then merge the result with dataset3
merged_1_2_3 = pd.merge(merged_1_2, dataset3, on='tconst', how='left')

# Continue the process with dataset4
merged_1_2_3_6 = pd.merge(merged_1_2_3, dataset6, on='tconst', how='left')

# Finally, merge with dataset6
merged_dataset = pd.merge(merged_1_2_3_6, dataset4, on='nconst', how='inner')

In [4]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
merged_dataset.head()

,tconst,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,...,ordering,nconst,category,job,characters,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,tt0000001,5.7,2007,short,Carmencita,Carmencita,0,1894,\N,1,...,2.0,nm0005690,director,\N,\N,William K.L. Dickson,1860,1935,"cinematographer,director,producer","tt0308254,tt0219560,tt1428455,tt1496763"
1,tt0000005,6.2,2697,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,...,3.0,nm0005690,director,\N,\N,William K.L. Dickson,1860,1935,"cinematographer,director,producer","tt0308254,tt0219560,tt1428455,tt1496763"
2,tt0000006,5.0,183,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,...,1.0,nm0005690,director,\N,\N,William K.L. Dickson,1860,1935,"cinematographer,director,producer","tt0308254,tt0219560,tt1428455,tt1496763"
3,tt0000007,5.4,842,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,...,3.0,nm0005690,director,\N,\N,William K.L. Dickson,1860,1935,"cinematographer,director,producer","tt0308254,tt0219560,tt1428455,tt1496763"
4,tt0000008,5.4,2154,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,...,2.0,nm0005690,director,\N,\N,William K.L. Dickson,1860,1935,"cinematographer,director,producer","tt0308254,tt0219560,tt1428455,tt1496763"

In [ ]:
netflix2 = pd.merge(netflix, merged_dataset, left_on='title', right_on='primaryTitle', how='left')

In [7]:
netflix2.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,ordering,nconst,category,job,characters,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,1.0,nm0385190,actor,\N,"[""Consultant""]",Michael Hilow,\N,\N,"stunts,actor","tt4477536,tt3553976,tt1740299,tt8772296"
1,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,2.0,nm11578174,actress,\N,"[""Backup Singer""]",Ana Hoffman,\N,\N,NaN,tt11394180
2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,1.0,nm0000215,actress,\N,"[""Narrator""]",Susan Sarandon,1946,\N,"actress,producer,soundtrack","tt0120686,tt0103074,tt0109446,tt0112818"
3,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,5.0,nm0809375,director,\N,\N,Mike Smith,\N,\N,"director,producer,writer","tt0461097,tt0808874,tt0403804,tt21229490"
4,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,1.0,nm0713761,actor,\N,"[""Mike Shepherd""]",Neill Rea,\N,\N,"actor,casting_director,assistant_director","tt0189981,tt1032751,tt3640276,tt0111999"

In [8]:
netflix3=df = netflix2.dropna(subset=['averageRating'])

In [9]:
netflix3.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'tconst', 'averageRating', 'numVotes', 'titleType', 'primaryTitle',
       'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes',
       'genres', 'directors', 'writers', 'ordering', 'nconst', 'category',
       'job', 'characters', 'primaryName', 'birthYear', 'deathYear',
       'primaryProfession', 'knownForTitles'],
      dtype='object')

In [10]:
netflix4 = netflix3.drop(columns=['listed_in', 'description','director', 'cast','duration', 'date_added','titleType','runtimeMinutes', 'tconst', 'titleType', 'primaryTitle',  'originalTitle', 'isAdult', 'startYear', 'endYear', 'writers', 'ordering', 'nconst', 'job', 'characters', 'birthYear', 'deathYear', 'primaryProfession', 'knownForTitles'])

In [11]:
netflix4.head()

,show_id,type,title,country,release_year,rating,averageRating,numVotes,genres,directors,category,primaryName
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13,7.4,7119.0,"Biography,Documentary,Drama",nm0990310,actor,Michael Hilow
1,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13,7.4,7119.0,"Biography,Documentary,Drama",nm0990310,actress,Ana Hoffman
2,s2,TV Show,Blood & Water,South Africa,2021,TV-MA,8.0,22.0,"Crime,Documentary",nm1520612,actress,Susan Sarandon
3,s2,TV Show,Blood & Water,South Africa,2021,TV-MA,7.3,528.0,"Crime,Drama,Mystery",nm0809375,director,Mike Smith
4,s2,TV Show,Blood & Water,South Africa,2021,TV-MA,7.3,528.0,"Crime,Drama,Mystery",nm0809375,actor,Neill Rea

In [13]:
netflix4.columns

Index(['show_id', 'type', 'title', 'country', 'release_year', 'rating',
       'averageRating', 'numVotes', 'genres', 'directors', 'category',
       'primaryName'],
      dtype='object')

In [14]:
netflix4.to_csv('netflix4.csv', index=False)

In [13]:
netflix4['genres'] = netflix4['genres'].str.split(',')

# Explode the 'genres' column into separate rows
netflix5 = netflix4.explode('genres')

# Now, exploded_genres DataFrame has separate rows for each genre of a movie

In [16]:

# 'genres' sütununu liste haline getirme ve one-hot encoding uygulama
netflix5['genres'] = netflix5['genres'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
mlb_genres = MultiLabelBinarizer()
genres_encoded = mlb_genres.fit_transform(netflix5['genres'])
genres_encoded_df = pd.DataFrame(genres_encoded, columns=mlb_genres.classes_)

# 'primaryName' sütununu işleme
netflix5['primaryName'] = netflix5['primaryName'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
mlb_names = MultiLabelBinarizer()
names_encoded = mlb_names.fit_transform(netflix5['primaryName'])
names_encoded_df = pd.DataFrame(names_encoded, columns=mlb_names.classes_)

# Kategoriye göre işleme (örneğin, director, actor, actress)
def categorize_names(names):
    categories = []
    for name in names:
        # Burada, ismin kategorisini belirleyen bir mantık olmalı.
        # Örnek olarak, her ismi 'director' olarak işaretliyorum.
        categories.append('director')  # Gerçek uygulamada bu, veri setinizdeki gerçek verilere göre değişmelidir.
    return categories

netflix5['name_categories'] = netflix5['primaryName'].apply(categorize_names)
mlb_categories = MultiLabelBinarizer()
categories_encoded = mlb_categories.fit_transform(netflix5['name_categories'])
categories_encoded_df = pd.DataFrame(categories_encoded, columns=mlb_categories.classes_)

# Son olarak, orijinal DataFrame ile encoded DataFrame'leri birleştirme
# ignore_index=True parametresini kaldırıyorum çünkü sütun isimlerini korumak istiyoruz.
df_encoded = pd.concat([netflix5, genres_encoded_df, names_encoded_df, categories_encoded_df], axis=1)

# Gereksiz sütunları kaldırma
df_encoded.drop(['genres', 'primaryName', 'name_categories'], axis=1, inplace=True)

# Yeni DataFrame'in ilk beş satırını gösterme
print(df_encoded.head())

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# 'genres' sütununu liste haline getirme ve one-hot encoding uygulama
netflix4['genres'] = netflix4['genres'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
mlb_genres = MultiLabelBinarizer()
genres_encoded = mlb_genres.fit_transform(netflix4['genres'])
genres_encoded_df = pd.DataFrame(genres_encoded, columns=mlb_genres.classes_)

# 'primaryName' sütununu işleme
netflix4['primaryName'] = netflix4['primaryName'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
mlb_names = MultiLabelBinarizer()
names_encoded = mlb_names.fit_transform(netflix4['primaryName'])
names_encoded_df = pd.DataFrame(names_encoded, columns=mlb_names.classes_)

# Kategoriye göre işleme
def categorize_names(names):
    categories = []
    for name in names:
        categories.append('director')  # Bu, örnek bir kategoridir.
    return categories

netflix4['name_categories'] = netflix4['primaryName'].apply(categorize_names)
mlb_categories = MultiLabelBinarizer()
categories_encoded = mlb_categories.fit_transform(netflix4['name_categories'])
categories_encoded_df = pd.DataFrame(categories_encoded, columns=mlb_categories.classes_)

# DataFrame'lerin indexlerini sıfırlama
netflix4.reset_index(drop=True, inplace=True)
genres_encoded_df.reset_index(drop=True, inplace=True)
names_encoded_df.reset_index(drop=True, inplace=True)
categories_encoded_df.reset_index(drop=True, inplace=True)

# DataFrame'leri birleştirme
df_encoded = pd.concat([netflix4, genres_encoded_df, names_encoded_df, categories_encoded_df], axis=1)

# Gereksiz sütunları kaldırma
df_encoded.drop(['genres', 'primaryName', 'name_categories'], axis=1, inplace=True)

# Yeni DataFrame'in ilk beş satırını gösterme
print(genres_encoded_df.head())

In [21]:
# 'genres' ve 'primaryName' için one-hot encoding uygulama
genres_dummies = pd.get_dummies(netflix5['genres'], prefix='Genre')
primaryName_dummies = pd.get_dummies(netflix5['primaryName'], prefix='Name')

# DataFrame'leri birleştirme
df_encoded = pd.concat([netflix5, genres_dummies, primaryName_dummies], axis=1)

# Orijinal 'genres' ve 'primaryName' sütunlarını kaldırma
df_encoded.drop(['genres', 'primaryName'], axis=1, inplace=True)

# Yeni DataFrame'in ilk beş satırını gösterme
print(df_encoded.head())

TypeError: unhashable type: 'list'